services:
    rables:
        image: versun/rables:latest
        environment:
            - RAILS_ENV=production
            - SECRET_KEY_BASE=b9b38205dfabbc0621116fb0557c155c
        ports:
            - "80:80"
        restart: unless-stopped
        volumes:
            - rables_storage:/rails/storage
volumes:
    rables_storage: